name: Java CI with TestNG and Selenium

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install -DskipTests=true
        
      - name: Start Selenoid
        uses: Xotabu4/selenoid-github-action@v2
        id: start-selenoid

      - name: Check Selenoid has been started
        run: curl http://localhost:4444/status
        
      - name: Run tests
        run: mvn test
